# Generated by Django 4.0.4 on 2022-06-13 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idProductomascota', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=70)),
                ('SexoProducto', models.CharField(max_length=1)),
                ('cantidadProducto', models.IntegerField()),
                ('fechaProducto', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
            ],
        ),
    ]
