# Generated by Django 4.0.4 on 2022-06-14 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=40, verbose_name='Nombre de la categoria'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='SexoProducto',
            field=models.CharField(max_length=1, verbose_name='Sexo de la mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='cantidadProducto',
            field=models.IntegerField(verbose_name='Cantidad de productos'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fechaProducto',
            field=models.DateField(verbose_name='Fecha del producto'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='idProductomascota',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del producto'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombreProducto',
            field=models.CharField(max_length=70, verbose_name='Nombre del producto'),
        ),
         migrations.AlterField(
            model_name='mascota',
            name='PrecioProducto',
            field=models.CharField(verbose_name='Precio del producto', default=999999),
        ),

    ]
