# Generated by Django 3.1.2 on 2022-07-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_categoria_idcategoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='PrecioProducto',
            field=models.IntegerField(default=999999, verbose_name='Precio del producto'),
        ),
    ]
