# Generated by Django 3.1.2 on 2022-07-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_mascota_precioproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='DescripcionProducto',
            field=models.CharField(default='Escriba aqui', max_length=306, verbose_name='Descripcion del producto'),
        ),
    ]
