# Generated by Django 3.1.2 on 2022-07-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_mascota_descripcionproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='cantidadProducto',
            field=models.IntegerField(max_length=2, verbose_name='Cantidad de productos'),
        ),
    ]
